import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css"
import Topbar from "../../../components/shared/Topbar";
import LeftSidebar from "../../../components/shared/LeftSidebar";
import Bottombar from "../../../components/shared/Bottombar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WebFrame Tech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full flex flex-col">
          
          <Topbar/>
          <div className="flex flex-row">
            <div className="flex-[20%]  "><LeftSidebar/></div>
           
            {children}
          </div>
          <Bottombar/>

        </div>
        
        </body>
    </html>
  );
}
